<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework> <!-- Likely the oldest compatiable framework due to usage of e.g. FrozenDictionary, init -->
	  <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnumClasses.SharedSources\EnumClasses.SharedSources.csproj" />
  </ItemGroup>

</Project>
