using System;

namespace EnumClasses
{
    /// <summary>
    /// Configures assembly-wide defaults for enum classes generated in the assembly.
    /// </summary>
    /// <remarks>
    /// Options specified directly on <see cref="EnumClassAttribute"/> or
    /// <see cref="NumberedEnumClassAttribute"/> take precedence over these defaults.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
#if ENUMCLASSES_SOURCE_GENERATOR
    internal class EnumClassDefaultsAttribute : Attribute
#else
    public class EnumClassDefaultsAttribute : Attribute
#endif
    {
        /// <summary>
        /// Gets or sets whether JSON converters are generated by default.
        /// </summary>
        public bool GenerateJsonConverter { get; set; } = DefaultGenerateJsonConverter;

        /// <summary>The built-in default for <see cref="GenerateJsonConverter"/>.</summary>
        public const bool DefaultGenerateJsonConverter = true;

        /// <summary>
        /// Gets or sets whether nested <c>Raw</c> enums and their conversions are generated by default.
        /// </summary>
        public bool GenerateRawEnum { get; set; } = DefaultGenerateRawEnum;

        /// <summary>The built-in default for <see cref="GenerateRawEnum"/>.</summary>
        public const bool DefaultGenerateRawEnum = false;

        /// <summary>
        /// Gets or sets how lookup implementations are selected by default.
        /// </summary>
        public LookupMode LookupMode { get; set; } = DefaultLookupMode;

        /// <summary>The built-in default for <see cref="LookupMode"/>.</summary>
        public const LookupMode DefaultLookupMode = LookupMode.Automatic;

        /// <summary>
        /// Gets or sets the constructor restrictions applied by default.
        /// </summary>
        public ConstructionRestrictionMode ConstructionRestrictionMode { get; set; } = DefaultConstructionRestrictionMode;

        /// <summary>The built-in default for <see cref="ConstructionRestrictionMode"/>.</summary>
        public const ConstructionRestrictionMode DefaultConstructionRestrictionMode = ConstructionRestrictionMode.WithProtectedDefaultConstructor;


        // NumberedEnumClass

        /// <summary>
        /// Gets or sets whether generated <c>EnumIndex</c> properties use the <see langword="required"/> modifier by default.
        /// </summary>
        public bool RequireIndexAssignmentInInitializer { get; set; } = DefaultRequireIndexAssignmentInInitializer;

        /// <summary>The built-in default for <see cref="RequireIndexAssignmentInInitializer"/>.</summary>
        public const bool DefaultRequireIndexAssignmentInInitializer = true;

    }
}
